/**
 * @file bitboard.cpp
 * @brief Implementation of the Bitboard class.
 * @author Generated by AI Assistant
 */

#include "bitboard.h"

/**
 * @brief Default constructor. Initializes all bitboards to 0 (all bits cleared).
 */
Bitboard::Bitboard() : player_board(0), opponent_board(0), red_board(0), blue_board(0) {}

/**
 * @brief Constructor with initial values for all bitboards.
 * @param player Player's bitboard initial value.
 * @param opponent Opponent's bitboard initial value.
 * @param red Red pieces bitboard initial value.
 * @param blue Blue pieces bitboard initial value.
 */
Bitboard::Bitboard(uint64_t player, uint64_t opponent, uint64_t red, uint64_t blue)
    : player_board(player), opponent_board(opponent), red_board(red), blue_board(blue) {}

/**
 * @brief Initializes all bitboards to 0.
 */
void Bitboard::init() {
    player_board = 0;
    opponent_board = 0;
    red_board = 0;
    blue_board = 0;
}

/**
 * @brief Initializes all bitboards to specific values.
 * @param player Player's bitboard value.
 * @param opponent Opponent's bitboard value.
 * @param red Red pieces bitboard value.
 * @param blue Blue pieces bitboard value.
 */
void Bitboard::init(uint64_t player, uint64_t opponent, uint64_t red, uint64_t blue) {
    player_board = player;
    opponent_board = opponent;
    red_board = red;
    blue_board = blue;
}