/**
 * @file bitboard.h
 * @brief Bitboard class implementation for efficient board representation.
 * @author Generated by AI Assistant
 */

#ifndef BITBOARD_H
#define BITBOARD_H

#include <cstdint>
#include <iostream>

/**
 * @class Bitboard
 * @brief A class to represent multiple bitboards for board games.
 * Contains bitboards for player pieces, opponent pieces, red pieces, and blue pieces.
 */
class Bitboard {
private:
    uint64_t player_board;    ///< Bitboard for player's pieces
    uint64_t opponent_board;  ///< Bitboard for opponent's pieces
    uint64_t red_board;       ///< Bitboard for red pieces
    uint64_t blue_board;      ///< Bitboard for blue pieces

public:
    /**
     * @brief Default constructor. Initializes all bitboards to 0 (all bits cleared).
     */
    Bitboard();

    /**
     * @brief Constructor with initial values for all bitboards.
     * @param player Player's bitboard initial value.
     * @param opponent Opponent's bitboard initial value.
     * @param red Red pieces bitboard initial value.
     * @param blue Blue pieces bitboard initial value.
     */
    Bitboard(uint64_t player, uint64_t opponent, uint64_t red, uint64_t blue);

    /**
     * @brief Initializes all bitboards to 0.
     */
    void init();

    /**
     * @brief Initializes all bitboards to specific values.
     * @param player Player's bitboard value.
     * @param opponent Opponent's bitboard value.
     * @param red Red pieces bitboard value.
     * @param blue Blue pieces bitboard value.
     */
    void init(uint64_t player, uint64_t opponent, uint64_t red, uint64_t blue);

    // Getters for individual bitboards
    uint64_t get_player_board() const { return player_board; }
    uint64_t get_opponent_board() const { return opponent_board; }
    uint64_t get_red_board() const { return red_board; }
    uint64_t get_blue_board() const { return blue_board; }

    // Additional methods can be added here for bit operations
};

#endif // BITBOARD_H